import graphene

class InterfaceDetails(graphene.ObjectType):
    interface = graphene.String()
    mac = graphene.String()
    type = graphene.String()
    mtu = graphene.String()
    metric = graphene.String()
    flags = graphene.String()
    ipackets = graphene.String()
    opackets = graphene.String()
    ibytes = graphene.String()
    obytes = graphene.String()
    ierrors = graphene.String()
    oerrors = graphene.String()
    idrops = graphene.String()
    odrops = graphene.String()
    last_change = graphene.String()
    description = graphene.String()
    manufacturer = graphene.String()
    connection_id = graphene.String()
    connection_status = graphene.String()
    enabled = graphene.String()
    physical_adapter = graphene.String()
    speed = graphene.String()
    dhcp_enabled = graphene.String()
    dhcp_lease_expires = graphene.String()
    dhcp_lease_obtained = graphene.String()
    dhcp_server = graphene.String()
    dns_domain = graphene.String()
    dns_domain_suffix_search_order = graphene.String()
    dns_host_name = graphene.String()
    dns_server_search_order = graphene.String()
