import graphene

class Processes(graphene.ObjectType):
    pid = graphene.String()
    name = graphene.String()
    path = graphene.String()
    cmdline = graphene.String()
    state = graphene.String()
    cwd = graphene.String()
    root = graphene.String()
    uid = graphene.String()
    gid = graphene.String()
    euid = graphene.String()
    egid = graphene.String()
    suid = graphene.String()
    sgid = graphene.String()
    on_disk = graphene.String()
    wired_size = graphene.String()
    resident_size = graphene.String()
    total_size = graphene.String()
    user_time = graphene.String()
    system_time = graphene.String()
    start_time = graphene.String()
    parent = graphene.String()
    pgroup = graphene.String()
    threads = graphene.String()
    nice = graphene.String()
